apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-pod 
    spec:
      containers:
        - image: {{ .Values.image_base }}/{{.Values.image}}:{{.Values.tag}}
          imagePullPolicy: Always
          name: {{ .Values.name }}-pod
          env:
            - name: DBHOST
              # Connect to the SQL proxy over the local network on a fixed port.
              # Change the [PORT] to the port number used by your database
              # (e.g. 3306).
              value: '{{ default "127.0.0.1:3306" .Values.dbhost }}'
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: DBPASS
              value: '{{ .Values.dbpass }}'
            - name: DBUSER
              value: '{{ default .Values.Name .Values.dbuser }}'
            - name: DBNAME
              value: '{{ default .Values.Name .Values.dbname }}'
            - name: SITENAME
              value: {{ .Values.name }}
            # [END cloudsql_secrets]
            - name: SMTPHOST
              value: {{ .Values.SMTPHOST }}
            - name: SMTPUSER
              value: {{ .Values.SMTPUSER }}
            - name: SMTPPASS
              value: {{ .Values.SMTPPASS }}
            - name: SMTP_FROM
              value: {{ .Values.SMTP_FROM }}
          ports:
            - containerPort: 8000
              name: wordpress
          resources:
            requests:
              memory: 1664Mi
            limits: 
              memory: 2048Mi
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /repo
          livenessProbe:
           httpGet:
             path: /healthz/index.html
             port: 8000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 3
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /healthz/index.html
             port: 8000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 3
           periodSeconds: 3
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-disk



